export const ADD_BOOKING = 'ADD_BOOKING';

export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL';

export const GET_BOOKING_BY_ID_REQUEST = 'GET_BOOKING_BY_ID_REQUEST';
export const GET_BOOKING_BY_ID_SUCCESS = 'GET_BOOKING_BY_ID_SUCCESS';
export const GET_BOOKING_BY_ID_FAIL = 'GET_BOOKING_BY_ID_FAIL';

